# Generated by Django 3.2.11 on 2022-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='channel_name',
            field=models.CharField(default='old', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='command',
            field=models.CharField(choices=[('YTDL', 'youtube-dl'), ('TWDL', 'twitch-dl')], default='TWDL', max_length=4),
        ),
        migrations.AddField(
            model_name='download',
            name='quality',
            field=models.CharField(default='720', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='size',
            field=models.CharField(default='30kb', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='slug_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('F', 'Failed'), ('C', 'Completed')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='download',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='download',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
