# Generated by Django 3.2.11 on 2022-02-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20220201_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='active_task_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
