# Generated by Django 3.2.11 on 2022-03-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_userprofile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='download.userprofile'),
            preserve_default=False,
        ),
    ]
