# Generated by Django 3.2.11 on 2022-02-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0003_download_active_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='download',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Started'), ('F', 'Failed'), ('C', 'Completed')], default='D', max_length=1),
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_code', models.CharField(max_length=100)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.extension')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.quality')),
            ],
        ),
        migrations.AddField(
            model_name='extension',
            name='qualities',
            field=models.ManyToManyField(through='download.Format', to='download.Quality'),
        ),
        migrations.AddField(
            model_name='download',
            name='choices_for',
            field=models.ManyToManyField(related_name='choices', to='download.Format'),
        ),
        migrations.AddField(
            model_name='download',
            name='file_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='download.format'),
        ),
    ]
