# Generated by Django 3.2.11 on 2022-02-08 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_auto_20220207_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='quality',
        ),
    ]
