# Generated by Django 3.2.11 on 2022-02-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0005_remove_download_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('YTDL', 'youtube-dl'), ('TWDL', 'twitch-dl')], default='TWDL', max_length=4)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='format',
            name='command',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='download.command'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='download',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.command'),
        ),
        migrations.AlterField(
            model_name='download',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='download.source'),
        ),
    ]
